apiVersion: v1
kind: Config
preferences: {}

# Define clusters
clusters:
  - name: my-cluster
    cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUyZ0F3SUJBZ0l...
      server: https://api.my-cluster.example.com:6443

# Define users
users:
  - name: my-user
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUyZ0F3SUJBZ0l...
      client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBd0V6b0R...

# Define contexts
contexts:
  - name: my-context
    context:
      cluster: my-cluster
      user: my-user
      namespace: default

# Set current context
current-context: my-context